### ISSUE TITLE
Concat just creating files named src and dest

### ISSUE THREAD

**Issue by wintercounter** [ariesjia/grunt-riot#12]
I'm using the following config to compile the files. It does compile, but only into an `src` file and also creates a `dest` file into the project root.

``` javascript
riot: {
    options: {
        concat : true
    },
    src: 'tags/**/*.tag',
    dest: 'js/tags.js'
}
```

**Comment by wintercounter** [comment]
I've checked the source and the documentation is wrong. Instead it should be:

``` javascript
riot: {
    compile: {
        options: {
            concat : true
        },
        src: 'tags/**/*.tag',
        dest: 'js/tags.js'
    }
}
```

I would create a pull request, but I don't have time now to check other cases as well, so sorry for that.

**Comment by ariesjia** [comment]
Thanks ,  i will update readme file
