### ISSUE TITLE
Compiling es6 fails

### ISSUE THREAD

**Issue by jbmartinez** [ariesjia/grunt-riot#13]
I'm trying to compile my tags with es6, but I get this warning: `Warning: unknown: Unexpected token (1:6)`. Both riot compiler and babel are installed.

It fails only when I try to compile with grunt, running `riot --type es6 tags-directory/` from the terminal works fine, producing all the tags compiled to JavaScript and preprocessed by babel.

I put this in the Gruntfile:

``` js
riot: {
      compile: {
        options: {
          concat: true,
          type: 'es6'
        },
        src: 'tags/**/*.tag',
        dest: '.tmp/app/tags/tags.js'
      }
    }
```

**Comment by ariesjia** [comment]
Hi , i test compile es6 is ok . but should attention words inner the  { }  also should use es6 syntax , Otherwise it will  fail .    '  unknown: Unexpected token (1:6) '   is  warning from babel

**Comment by jbmartinez** [comment]
I already converted my tags to es5, but I added this tag to my project just for testing and it worked fine:

``` html
<test-tag>
    <div>
        <p>{ someText() }</p>
    </div>

    <script type="es6">
        this.someText = () => 'This works!';
    </script>
</test-tag>
```

My original tags didn't look too different to that and I still wonder why they were compiled fine from the command line but failed with grunt-riot.

My project is almost completed, anyway. Thanks for this great tool!
