### ISSUE TITLE
Doesn't work with es6

### ISSUE THREAD

**Issue by phillip-haydon** [ariesjia/grunt-riot#15]
I donno if your docs are lacking or if its broken. But this doesn't seem to work with babel. 

Running "riot:tags" (riot) task
Warning: Cannot find module 'babel' Use --force to continue.

babel-core (and tried babel too) are installed, but it fails.

I've ripped out grunt-riot from my app and moved my few things to gulp to get this working.

**Comment by halbgut** [comment]
This issue seems to come from riot itself. They have a bug in their Babel 6 integration. So you'll need to use `babel@5.8`  with `"es6"` as `type`.

You'll need to

``` bash
$ npm i --save-dev babel@5.8
```

And in your gruntfile

``` json
type: 'es6'
```

**Comment by phillip-haydon** [comment]
I moved to Gulp-Riot instead, I just set the type as babel and everything just works. 

Thanks.
