### ISSUE TITLE
failed optional dependency /chokidar/fsevents

### ISSUE THREAD

**Issue by luixxiul** [ariesjia/grunt-riot#16]
On Windows 10 `npm update` returns:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm WARN optional Skipping failed optional dependency /grunt-riot/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
```

 Is it a kind of error?

**Comment by AkessonHenrik** [comment]
Try using the `--no-optional` flag as a workaround.

`npm update --no-optional`

**Comment by luixxiul** [comment]
Clean installing worked for some reason.

**Comment by xiongyu1988** [comment]
clean installing?

**Comment by ghost** [comment]
@luixxiul how to clean intalling work for some reason?

**Comment by luixxiul** [comment]
````
rm -rf node_modules
npm i
```

**Comment by mfinkelstine** [comment]
Hi, 

any idea how to solve this issue 

abcd@abcdMINGW64 /d/nodejsProjects/perfResults (master)
$ npm i -S  fsevents
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "D:\Users\abcd\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "i" "-S" "fsevents"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.3
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     D:\nodejsProjects\perfResults\npm-debug.log

**Comment by vjpr** [comment]
@mfinkelstine Somewhere in your dependency tree, `fsevents` is listed in a `package.json` under `dependencies`, when it should be `optionalDependencies`.

Run `npm ls` to view your dependency tree and you will find the culprit!

**Comment by matheusasdev** [comment]
I was receiving this error when I was using Guake Terminal in Ubuntu 18.04. Then, I uninstalled nodejs and  npm using the Ubuntu Terminal (because I was having errors of permission in node files) and then I installed them again. So, I didn't have more problems at the npm install.
