### ISSUE TITLE
Support for >= 2.3

### ISSUE THREAD

**Issue by f1ana** [ariesjia/grunt-riot#17]
Is there a reason why Riot < 2.3 is in dev dependencies?  I have been using this with Riot 2.2.4 with no issues but anything above 2.3 throws strange errors.
Is the solution as simple as adjusting the dev dependencies or are there larger issues at play?

**Comment by ariesjia** [comment]
Thanks ,  I update to 2.3 , and tested .   It worsk .  
pls  update  to  0.1.15
