### ISSUE TITLE
Compile to a single concatenated file

### ISSUE THREAD

**Issue by pixelkritzel** [ariesjia/grunt-riot#2]
Is there a option to compile all my tag files to a single concatenated file?

**Comment by ariesjia** [comment]
not support  yet ,  I will add this feature  in next version .

**Comment by dotnetchris** [comment]
+1

**Comment by ariesjia** [comment]
sorry to commit late , i add  `concat`  in option  . you can set config like this :

```
concatFile: {
        options: {
            concat : true
        },
        src: 'script/*.tag',
        dest: '.tmp/tag.js'
}
```

**Comment by pixelkritzel** [comment]
Thank you!
