### ISSUE TITLE
How concat should work?

### ISSUE THREAD

**Issue by lanwin** [ariesjia/grunt-riot#3]
Ive tried concat, but it dont seems to change anything. I would expect to give a file on dest instead of a directory and then concat merge all tag files into that dest file. 

I put an console.log into the this.files.forEach and can see that this is called mutliple times and I would assume it should not when usinging concat.

If I do something work, please put an example into the readme so everyone can see how it should be. 

``` json
{
  options: {
    concat: true
  },
  dist: {
     expand: true,
     cwd: 'src',
     src: '**/*.tag',
     dest: 'build',
     ext: '.js'
  }
}
```

**Comment by ariesjia** [comment]
thanks for you commit , 

you can set config like this ,  take care not to  set  `expand: true` option , here is example.

``` js
concatFile: {
        options: {
            concat : true
        },
        src: 'script/*.tag',
        dest: '.tmp/tag.js'
}
```

I will update this example to reademe file. 
thank you .

**Comment by lanwin** [comment]
THX! Works well now. The funny thing is that I though I had tried this.....
